# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea7aab30779ce0b9fec3c175762e66dcb893fc8b0f8a897cfa42425e69a8ad2db04c5e4e329450a05a2a5871923ddea77aa7e0a13a23475a3d5163948e80dde

test:
  secret_key_base: 02d985d06b6160044b32ae3299053667f2d10e752def66341283052b0edd8dc260065649ec107509be870b39393577536f0fccaf00a2153b343ee902eb5ebc9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
